
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass